### PR TITLE
Emit better warning when parsing snapshot header fails

### LINKED ISSUE #1049: Emit better warning if parsing the `SnapshotHeader` fails

### PR DESCRIPTION
**Pull request by grtlr**
## Links to any relevant issues

Closes #1049.

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes
- [x] I have updated the CHANGELOG.md, if my changes are significant enough

### CODE REVIEW

File: bee-ledger/src/workers/snapshot/download.rs [hunk 1]
```diff
@@ -37,7 +37,10 @@ async fn download_snapshot_header(download_url: &str) -> Result<SnapshotHeader,
 
                         let mut slice: &[u8] = &bytes[..SnapshotHeader::LENGTH];
 
-                        return Ok(SnapshotHeader::unpack(&mut slice)?);
+                        return SnapshotHeader::unpack(&mut slice).map_err(|_| {
+                            warn!("Could not parse snapshot header from {}.", download_url);
+                            Error::ParsingSnapshotHeaderFailed
```
Comment (thibault-martinez) [inline bee-ledger/src/workers/snapshot/download.rs]: Can we embed the error ? Would be easier for us to debug in case of issue

**Review by thibault-martinez — APPROVED** [review]

**Review by pvdrz — APPROVED** [review]

**Review by Adam-Gleave — APPROVED** [review]
