### PR TITLE
Fix removal of disconnected peers in the peer manager

### LINKED ISSUE #1143: Some autopeered peers are kept even if not connected

### PR DESCRIPTION
**Pull request by Alex6323**
# Description of change

* Improves detection of a valid connection by making use of `libp2p` identify protocol;
* Fixes notification of removed peers in `bee-gossip` so that the peer manager in `bee-protocol` removes all disconnected peers appropriatedly;
* Improves logs;

## Links to any relevant issues

Fixes #1143 

## Type of change

- Enhancement (a non-breaking change which adds functionality)
- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

VPS

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes
- [x] I have updated the CHANGELOG.md, if my changes are significant enough

### CODE REVIEW

File: bee-network/bee-autopeering/src/peer/peer_id.rs [hunk 1]
```diff
@@ -98,7 +98,7 @@ impl fmt::Debug for PeerId {
 
 impl fmt::Display for PeerId {
     fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
-        self.libp2p_peer_id().to_base58()[..DISPLAY_LENGTH].fmt(f)
+        self.libp2p_peer_id().to_base58()[8..8+DISPLAY_LENGTH].fmt(f)
```
Comment (thibault-martinez) [inline bee-network/bee-autopeering/src/peer/peer_id.rs]: Any constant we could use instead of raw 8 ?

File: bee-network/bee-gossip/src/service/event.rs [hunk 2]
```diff
@@ -100,6 +100,13 @@ pub enum Event {
         /// The peer's id.
         peer_id: PeerId,
     },
```
Comment (thibault-martinez) [inline bee-network/bee-gossip/src/service/event.rs:102]:
```suggestion
    },
    
```
For consistency in this file even though it's not consistent with the rest of the project.

**Review by thibault-martinez — CHANGES_REQUESTED** [review]

File: bee-network/bee-autopeering/src/peer/peer_id.rs (hunk 1 above)
Comment (Alex6323) [reply bee-network/bee-autopeering/src/peer/peer_id.rs]: sure ~> I'll introduce DISPLAY_OFFSET

**Review by pvdrz — DISMISSED** [review]

File: bee-network/bee-gossip/src/service/event.rs (hunk 2 above)
Comment (thibault-martinez) [reply bee-network/bee-gossip/src/service/event.rs:102]: Don't forget this please :)

File: bee-network/bee-autopeering/src/task.rs [hunk 3]
```diff
@@ -117,7 +117,10 @@ impl<S: PeerStore> TaskManager<S> {
             let shutdown_tx = shutdown_senders.remove(&task_name).unwrap();
 
             log::trace!("Shutting down: {}", task_name);
-            shutdown_tx.send(()).expect("error sending shutdown signal");
+
+            if shutdown_tx.send(()).is_err() {
+                log::error!("Error sending shutdown signal to task {task_name}. This is a bug.");
```
Comment (thibault-martinez) [inline bee-network/bee-autopeering/src/task.rs]: I wouldn't put "This is a bug." it's kinda obvious since this is an error log.

File: bee-network/bee-gossip/src/alias.rs [hunk 4]
```diff
@@ -7,9 +7,9 @@
 #[macro_export]
 macro_rules! alias {
     ($peer_id:expr) => {
-        &$peer_id.to_base58()[46..]
+        &$peer_id.to_base58()[8..24]
```
Comment (thibault-martinez) [inline bee-network/bee-gossip/src/alias.rs:10]: Looks like the constants from the other crate ? No way to reuse them ?

File: bee-network/bee-gossip/src/service/host.rs [hunk 5]
```diff
@@ -1,6 +1,8 @@
 // Copyright 2020-2021 IOTA Stiftung
 // SPDX-License-Identifier: Apache-2.0
 
+use std::time::{SystemTime, UNIX_EPOCH};
```
Comment (thibault-martinez) [inline bee-network/bee-gossip/src/service/host.rs]: After 3rd parties

File: bee-network/bee-gossip/src/swarm/protocols/iota_gossip/io.rs [hunk 6]
```diff
@@ -53,15 +53,13 @@ pub fn start_incoming_processor(
...
-                // The remote peer dropped the connection.
-                internal_event_sender
-                    .send(InternalEvent::ProtocolDropped { peer_id })
-                    .expect("The service must not shutdown as long as there are gossip tasks running.");
-
                 break;
             }
         }
 
+        // Ignore send errors.
```
Comment (thibault-martinez) [inline bee-network/bee-gossip/src/swarm/protocols/iota_gossip/io.rs]: Just curious: why ?

File: bee-network/bee-gossip/CHANGELOG.md [hunk 7]
```diff
@@ -19,6 +19,21 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 
 ### Security -->
 
+## 0.5.0 - 2022-02-28
+
+### Added
+
+- `PeerMetrics` type, that keeps a count of dial attempts and idenfication timestamp;
+- `PeerUnreachable` event: fired after a certain number of unsuccessful dial attempts;
```
Comment (grtlr) [inline bee-network/bee-gossip/CHANGELOG.md]:
```suggestion
- `PeerMetrics` type that keeps a count of dial attempts and identification timestamp;
- `PeerUnreachable` event that is fired after a certain number of unsuccessful dial attempts;
```

File: bee-api/bee-rest-api/Cargo.toml [hunk 8]
```diff
@@ -12,7 +12,7 @@ homepage = "https://www.iota.org"
 
 [dependencies]
 bee-common = { version = "0.6.0", path = "../../bee-common/bee-common", default-features = false, optional = true }
-bee-gossip = { version = "0.4.0", path = "../../bee-network/bee-gossip", default-features = false, optional = true }
+bee-gossip = { version = "0.5.0", path = "../../bee-network/bee-gossip", default-features = false, optional = true }
```
Comment (thibault-martinez) [inline bee-api/bee-rest-api/Cargo.toml:15]: The crate itself probably needs a little bump

File: bee-network/bee-gossip/src/swarm/behaviour.rs [hunk 9]
```diff
@@ -43,13 +43,13 @@ impl NetworkBehaviourEventProcess<IdentifyEvent> for SwarmBehaviour {
...
-                trace!(
-                    "Received Identify request from {}. Observed address: {:?}.",
-                    alias!(peer_id),
-                    info.observed_addr,
-                );
+                trace!("Received Identify response from {}: {:?}.", alias!(peer_id), info,);
 
-                // TODO: log supported protocols by the peer (info.protocols)
+                // Panic:
+                // Sending must not fail.
```
Comment (thibault-martinez) [inline bee-network/bee-gossip/src/swarm/behaviour.rs]: For panic comments I would usually expect the reason why we can be sure it will not fail.
Just stating it must not fail is redundant with the fact we have an expect in the first place.

File: bee-network/bee-gossip/src/service/event.rs [hunk 10]
```diff
@@ -123,8 +131,20 @@ pub enum InternalEvent {
         substream: Box<NegotiatedSubstream>,
     },
 
-    /// The gossip protocol has been dropped with a peer.
-    ProtocolDropped { peer_id: PeerId },
+    /// The gossip protocol with a peer was stopped.
+    ProtocolStopped { peer_id: PeerId },
```
Comment (thibault-martinez) [inline bee-network/bee-gossip/src/service/event.rs]: `peer_id` is not documented (for consistency)

File: bee-network/bee-gossip/src/swarm/behaviour.rs (hunk 9 above)
Comment (thibault-martinez) [reply bee-network/bee-gossip/src/swarm/behaviour.rs]: Also, I would put both comments in the same line.

File: bee-network/bee-gossip/src/peer/list.rs [hunk 11]
```diff
@@ -77,29 +78,21 @@ impl PeerList {
         }
     }
 
-    pub fn insert_peer(&mut self, peer_id: PeerId, peer_info: PeerInfo) -> Result<(), (PeerId, PeerInfo, Error)> {
+    pub fn add(&mut self, peer_id: PeerId, peer_info: PeerInfo) -> Result<(), (PeerId, PeerInfo, Error)> {
```
Comment (grtlr) [inline bee-network/bee-gossip/src/peer/list.rs:81]: Do we ever need `PeerId` and `PeerInfo` in the `Result::Err`? Most of the time the code immediately calls `.map_err()` to extract the `Error`. It looks like the only time we use `PeerId` and `PeerInfo` is marked with a `TODO`. We could also make `PeerInfo` a part of `Error::PeerIsDuplicate`.

Comment (Alex6323) [reply bee-network/bee-gossip/src/peer/list.rs:81]: Will be fixed in #1174.

File: bee-network/bee-gossip/src/service/event.rs (hunk 10 above)
Comment (Alex6323) [reply bee-network/bee-gossip/src/service/event.rs]: Fixed

File: bee-network/bee-gossip/src/swarm/behaviour.rs (hunk 9 above)
Comment (Alex6323) [reply bee-network/bee-gossip/src/swarm/behaviour.rs]: you're right :+1:

File: bee-api/bee-rest-api/Cargo.toml (hunk 8 above)
Comment (Alex6323) [reply bee-api/bee-rest-api/Cargo.toml:15]: what's going on there? I could not have it compiled without that bump. Why are you seeing this?

Comment (thibault-martinez) [reply bee-api/bee-rest-api/Cargo.toml:15]: I was just saying bee-rest-api itself may need a bump, like you did with the protocol

File: bee-network/bee-gossip/src/swarm/protocols/iota_gossip/io.rs (hunk 6 above)
Comment (Alex6323) [reply bee-network/bee-gossip/src/swarm/protocols/iota_gossip/io.rs]: we have a stronger guarantee here. It cannot panic. I changed it.

File: bee-api/bee-rest-api/Cargo.toml (hunk 8 above)
Comment (Alex6323) [reply bee-api/bee-rest-api/Cargo.toml:15]: oh damn, that wasn't a suggested change from you, haha. Did I have enough sleep last night? :joy:

Comment (Alex6323) [reply bee-api/bee-rest-api/Cargo.toml:15]: Done

File: bee-network/bee-gossip/src/service/host.rs (hunk 5 above)
Comment (Alex6323) [reply bee-network/bee-gossip/src/service/host.rs]: Done, thx

File: bee-network/bee-gossip/src/alias.rs (hunk 4 above)
Comment (Alex6323) [reply bee-network/bee-gossip/src/alias.rs:10]: I will ... but very clean in PR #1174. There are some things that `bee-gossip` and `bee-autopeering` have in common. Those things will move into a `bee-network` crate. Neither `bee-gossip` nor `bee-autopeering` should depend on each other as they are completely different things.

File: bee-network/bee-autopeering/src/task.rs (hunk 3 above)
Comment (Alex6323) [reply bee-network/bee-autopeering/src/task.rs]: Removed.

File: bee-network/bee-gossip/src/swarm/protocols/iota_gossip/io.rs [hunk 12]
```diff
@@ -28,89 +28,80 @@ pub fn channel() -> (GossipSender, GossipReceiver) {
...
+                if inbound_gossip_tx.send(buf[..len].to_vec()).is_err() {
+                    debug!("Terminating gossip protocol with {}.", alias!(peer_id));
 
-                    // The receiver of this channel was dropped, maybe due to a shutdown. There is nothing we can do
-                    // to salvage this situation, hence we drop the connection.
                     break;
                 }
             } else {
-                debug!("gossip-in: stream closed remotely.");
+                debug!("Peer {} terminated gossip protocol.", alias!(peer_id));
```
Comment (Adam-Gleave) [inline bee-network/bee-gossip/src/swarm/protocols/iota_gossip/io.rs:53]: The nesting here is a little bit difficult to read imo, could it be reorganised?

Comment (Alex6323) [reply bee-network/bee-gossip/src/swarm/protocols/iota_gossip/io.rs:53]: This code is completely going away in #1174, because `bee-protocol` will have direct access to the underlying socket instead of this "forwarding" logic here.

**Review by samuel-rufi — DISMISSED** [review]

**Review by grtlr — DISMISSED** [review]

File: bee-network/bee-gossip/src/swarm/protocols/iota_gossip/io.rs (hunk 12 above)
Comment (Adam-Gleave) [reply bee-network/bee-gossip/src/swarm/protocols/iota_gossip/io.rs:53]: Ah, no worries 👍

**Review by Adam-Gleave — DISMISSED** [review]

File: bee-network/bee-gossip/src/network/host.rs [hunk 13]
```diff
@@ -209,13 +206,36 @@ async fn dial_peer(swarm: &mut Swarm<SwarmBehaviour>, peer_id: PeerId, peerlist:
...
+    );
 
     // TODO: We also use `Swarm::dial_addr` here (instead of `Swarm::dial`) for now. See if it's better to change
     // that.
     Swarm::dial_addr(swarm, addr).map_err(|e| Error::DialingPeerFailed(peer_id, e))?;
 
     Ok(())
 }
+
+async fn hang_up(swarm: &mut Swarm<SwarmBehaviour>, peer_id: PeerId) {
```
Comment (thibault-martinez) [inline bee-network/bee-gossip/src/network/host.rs:237]: Doesn't seem to need the async ?
Also, you don't do a function for the other events, I wouldn't for consistency.

File: bee-network/bee-gossip/src/peer/list.rs [hunk 14]
```diff
@@ -77,29 +78,21 @@ impl PeerList {
...
-
-        let _ = self.local_addrs.insert(addr);
+        let _ = self
+            .peers
+            .insert(peer_id, (peer_info, PeerState::default(), PeerMetrics::default()));
 
         Ok(())
     }
 
     pub fn remove(&mut self, peer_id: &PeerId) -> Result<PeerInfo, Error> {
```
Comment (thibault-martinez) [inline bee-network/bee-gossip/src/peer/list.rs:94]: API is a tiny bit uncommon, you'd usually return an Option<PeerInfo>

File: bee-network/bee-gossip/src/peer/list.rs [hunk 15]
```diff
@@ -112,18 +105,36 @@ impl PeerList {
         self.peers
             .get(peer_id)
             .ok_or(Error::PeerNotPresent(*peer_id))
-            .map(|(peer_info, _)| peer_info.clone())
+            .map(|(info, _, _)| info.clone())
+    }
+
+    pub fn metrics(&self, peer_id: &PeerId) -> Result<PeerMetrics, Error> {
```
Comment (thibault-martinez) [inline bee-network/bee-gossip/src/peer/list.rs:111]: Same

File: bee-network/bee-gossip/src/peer/list.rs [hunk 16]
```diff
@@ -112,18 +105,36 @@ impl PeerList {
...
         self.peers.len()
     }
 
+    /// Note: Returns an error if the address trying to be added is a duplicate.
+    pub fn add_local_addr(&mut self, addr: Multiaddr) -> Result<(), (Multiaddr, Error)> {
+        if self.local_addrs.contains(&addr) {
+            return Err((addr.clone(), Error::AddressIsDuplicate(addr)));
+        }
+
+        let _ = self.local_addrs.insert(addr);
```
Comment (thibault-martinez) [inline bee-network/bee-gossip/src/peer/list.rs]: Why not use the result to conditionally return ? One less hash.

File: bee-network/bee-gossip/src/peer/list.rs [hunk 17]
```diff
@@ -475,6 +498,12 @@ pub enum PeerState {
     Connected(GossipSender),
 }
 
+#[derive(Clone, Debug, Default)]
+pub struct PeerMetrics {
+    pub(crate) num_dials: usize,
+    pub(crate) identified: Option<u64>,
```
Comment (thibault-martinez) [inline bee-network/bee-gossip/src/peer/list.rs]: It's not obvious to me what this actually represent. Given the name I would expect a boolean.

**Review by thibault-martinez — CHANGES_REQUESTED** [review]

File: bee-protocol/src/workers/peer/manager.rs [hunk 18]
```diff
@@ -202,21 +214,25 @@ fn handle_new_peering(peer: bee_autopeering::Peer, network_name: &str, command_t
     if let Some(multiaddr) = peer.service_multiaddr(network_name) {
         let peer_id = peer.peer_id().libp2p_peer_id();
 
+        // Panic:
+        // Sending commands must not fail.
```
Comment (thibault-martinez) [inline bee-protocol/src/workers/peer/manager.rs]: An actual explanation would be nice

File: bee-protocol/src/workers/peer/manager.rs [hunk 19]
```diff
@@ -202,21 +214,25 @@ fn handle_new_peering(peer: bee_autopeering::Peer, network_name: &str, command_t
...
-            .expect("error sending network command");
+            .expect("send command to gossip layer");
     }
 }
 
 fn handle_peering_dropped(peer_id: bee_autopeering::PeerId, command_tx: &NetworkCommandSender) {
     let peer_id = peer_id.libp2p_peer_id();
 
+    // Panic:
+    // Sending commands must not fail.
```
Comment (thibault-martinez) [inline bee-protocol/src/workers/peer/manager.rs]: Same

File: bee-protocol/src/workers/peer/manager.rs [hunk 20]
```diff
@@ -187,6 +189,16 @@ where
                             info!("Disconnected peer {}.", peer.0.alias());
                         })
                         .unwrap_or_default(),
+                    NetworkEvent::PeerUnreachable { peer_id, peer_info } => {
```
Comment (thibault-martinez) [inline bee-protocol/src/workers/peer/manager.rs:192]: Why are we delegating this to the protocol ? We're just sending a command back to the gossip so why can't it be all done internally ?

File: bee-network/bee-gossip/src/service/host.rs [hunk 21]
```diff
@@ -213,37 +217,47 @@ async fn peerstate_checker(shutdown: Shutdown, senders: Senders, peerlist: PeerL
...
         let num_connected_discovered =
-            peerlist_reader.filter_count(|info, state| info.relation.is_discovered() && state.is_connected());
+            read.filter_count(|info, state, _| info.relation.is_discovered() && state.is_connected());
+
+        // How many peers we know of but are currently disconnected.
+        let num_disconnected = read.filter_count(|_, state, _| state.is_disconnected());
 
         info!(
-            "Connected peers: known {}/{} unknown {}/{} discovered {}/{}.",
+            "Connected peers: known {}/{} unknown {}/{} discovered {}/{} - Disconnected peers: {}.",
```
Comment (thibault-martinez) [inline bee-network/bee-gossip/src/service/host.rs:238]:
```suggestion
            "Connected peers: known {}/{} unknown {}/{} discovered {}/{} disconnected {}.",
```
I think this would be more consistent

File: bee-network/bee-gossip/src/network/host.rs (hunk 13 above)
Comment (Alex6323) [reply bee-network/bee-gossip/src/network/host.rs:237]: No, it's not needed atm (in fact it won't ever be due to #1174), but decided to add it because the "nature" of those functions is the same. It's not unlikely that in the (in fact not happening) future `hang_up` may require access to the `peerlist` which is protected by an async lock.

The second sentence I don't understand. This is a command handler just as `dial_addr` and `dial_peer`. What's different here is that I don't return an error (which I could do for consistency, but decided against it to keep the changes as small as possible in this PR)

File: bee-network/bee-gossip/src/peer/list.rs (hunk 14 above)
Comment (Alex6323) [reply bee-network/bee-gossip/src/peer/list.rs:94]: Yes, you're right, and I kept this API only to be consistent with the old code. I will be much more strict with a common API in #1174, so hopefully no surprises there :smile:

File: bee-network/bee-gossip/src/network/host.rs (hunk 13 above)
Comment (thibault-martinez) [reply bee-network/bee-gossip/src/network/host.rs:237]: Yeah I'm just not sure if the compiler will create a state machine for it or not. In doubt, if not needed I wouldn't put it. Ignore the second sentence, I confused myself 🙃

File: bee-network/bee-gossip/src/peer/list.rs (hunk 15 above)
Comment (Alex6323) [reply bee-network/bee-gossip/src/peer/list.rs:111]: Same answer :trollface:

File: bee-network/bee-gossip/src/peer/list.rs (hunk 16 above)
Comment (Alex6323) [reply bee-network/bee-gossip/src/peer/list.rs]: you're right...I guess it used to be a HashMap before at some point, and that would have replaced the value.

File: bee-network/bee-gossip/src/peer/list.rs (hunk 17 above)
Comment (Alex6323) [reply bee-network/bee-gossip/src/peer/list.rs]: Since it's an `Option` it's kinda like a boolean: `None` ~> not identified, `Some(timestamp)` ~> "identified at".

Comment (Adam-Gleave) [reply bee-network/bee-gossip/src/peer/list.rs]: `identified_at` might be a better name, usually `Option`s seem to be named as if they were `Some(name)`.

File: bee-protocol/src/workers/peer/manager.rs (hunk 18 above)
Comment (Alex6323) [reply bee-protocol/src/workers/peer/manager.rs]: Added

File: bee-protocol/src/workers/peer/manager.rs (hunk 19 above)
Comment (Alex6323) [reply bee-protocol/src/workers/peer/manager.rs]: Added

File: bee-network/bee-gossip/src/service/host.rs (hunk 21 above)
Comment (grtlr) [reply bee-network/bee-gossip/src/service/host.rs:238]:
```suggestion
            "Peers: known {}/{} unknown {}/{} discovered {}/{} disconnected {}.",
```

File: bee-protocol/src/workers/peer/manager.rs (hunk 20 above)
Comment (Alex6323) [reply bee-protocol/src/workers/peer/manager.rs:192]: Because how manual peers and auto peers are treated may be a higher level protocol decision. It's just reporting back whether establishing a gossip connection with a peer (as ordered by bee-protocol) succeeded or not. In this case it was ordered to establish a connection to `peer_id`, it tried a few times, and then reports back that the peer is ... well, unreachable at the moment. `bee-protocol` can now decide what to do with that information. For discovered peers it makes sense to tell `bee-autopeering` to remove that peer from the neighborhood, for "manual" peers it may decide to log a warning about a configuration issue. Since `bee-gossip` and `bee-autopeering` don't know about each other for good reason (it would be wrong to make `bee-gossip` dependent on `bee-autopeering`), we need to delegate this to a higher level (`bee-protocol`).

At least that's how I see how these things should be architectured. Doesn't mean I am right of course.

File: bee-network/bee-gossip/src/service/host.rs (hunk 21 above)
Comment (Alex6323) [reply bee-network/bee-gossip/src/service/host.rs:238]: I am willing to change the log output, but the suggested change is illogical to me:
"Connected peers: ....... disconnected {}." hurts my brain too much :joy: I am open to other suggestions though.

Comment (thibault-martinez) [reply bee-network/bee-gossip/src/service/host.rs:238]: Yeah Jochen's one is better

File: bee-network/bee-gossip/src/network/host.rs (hunk 13 above)
Comment (Alex6323) [reply bee-network/bee-gossip/src/network/host.rs:237]: That's actually something worth to know. I will try to find something on it online. I had my hopes up that the compiler would be smart enough to remove syntactic sugar automatically, but here I may be wrong.

File: bee-network/bee-gossip/src/peer/list.rs (hunk 17 above)
Comment (Alex6323) [reply bee-network/bee-gossip/src/peer/list.rs]: Alright, then. Makes sense Adam.

Comment (Alex6323) [reply bee-network/bee-gossip/src/peer/list.rs]: Done

File: bee-network/bee-gossip/src/service/host.rs (hunk 21 above)
Comment (Alex6323) [reply bee-network/bee-gossip/src/service/host.rs:238]: So that in "{1}/{2}" 1 means "connected", and not "healthy", "sync", "in love with" is obvious?

Comment (Alex6323) [reply bee-network/bee-gossip/src/service/host.rs:238]: I still like the original much more. I don't see where it's inconsistent, and removing the "Connected" makes things a bit vague, although a 3 year old is probably right in guessing here.

**Review by thibault-martinez — APPROVED** [review]

**Review by grtlr — APPROVED** [review]

**Review by Adam-Gleave — APPROVED** [review]

File: bee-network/bee-gossip/src/service/host.rs (hunk 21 above)
Comment (Alex6323) [reply bee-network/bee-gossip/src/service/host.rs:238]: Okay, since you approved, I am closing this noting that I am not against a change at all, just think, that the suggested proposals have problems of their own :wink:
