### PR TITLE
Fix peer manager deadlock

### LINKED ISSUE #985: Bee doesn't stop
## Bug description

If I stop my bee service not all plugins get stopped and I can wait for more than 15min but Bee still doesn't stop...

## Rust version

- Rust version: 1.57.0

## Bee version

- Bee version (version number, commit, or branch): 7fbbfabb

## Hardware specification

- Operating system: Ubuntu
- RAM: 4GB
- Cores: 3 
 
## Steps To reproduce the bug

Stop Bee

## Errors

[bee_logs.txt](https://github.com/iotaledger/bee/files/7892715/bee_logs.txt)

### PR DESCRIPTION
**Pull request by pvdrz**
# Description of change

Avoid nested read guard acquisition over the `PeerManager` lock in the same function which causes a deadlock. See https://docs.rs/parking_lot/latest/parking_lot/type.RwLock.html for more details. In particular:

> This lock uses a task-fair locking policy which avoids both reader and writer starvation. This means that readers trying to acquire the lock will block even if the lock is unlocked when there are writers waiting to acquire the lock. Because of this, attempts to recursively acquire a read lock within a single thread may result in a deadlock.

Also the `RwLock` field has been made private to keep all the ways of accessing this lock as methods of the struct that contains it.

## Links to any relevant issues

Fixes https://github.com/iotaledger/bee/issues/985 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

The node was run twice for 30 and 60 minutes and the deadlock did not happen

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes
- [x] I have updated the CHANGELOG.md, if my changes are significant enough

### CODE REVIEW

File: bee-protocol/src/workers/peer/manager_res.rs [hunk 1]
```diff
@@ -54,7 +54,7 @@ pub struct PeerManagerInner {
 
 #[derive(Default)]
 // TODO private
```
Comment (thibault-martinez) [inline bee-protocol/src/workers/peer/manager_res.rs]: remove

**Review by samuel-rufi — DISMISSED** [review]

File: bee-protocol/src/workers/peer/manager_res.rs [hunk 2]
```diff
@@ -96,6 +94,26 @@ impl PeerManager {
         self.0.read().peers.iter().for_each(|(id, (peer, _))| f(id, peer));
     }
 
+    pub(crate) fn find_first_fairly(&self, counter: &mut usize, f: impl Fn(&Peer) -> bool) -> Option<PeerId> {
```
Comment (thibault-martinez) [inline bee-protocol/src/workers/peer/manager_res.rs]: Do you think we can make the counter internal ? API would be cleaner.

Comment (thibault-martinez) [reply bee-protocol/src/workers/peer/manager_res.rs]: Actually I think it should be internal, it's the only way to guarantee 100% fairness.

Comment (pvdrz) [reply bee-protocol/src/workers/peer/manager_res.rs]: I will make it internal. I was thinking on removing the `first` as I think it is redundant. `Iterator::find` already stops on the first match

Comment (thibault-martinez) [reply bee-protocol/src/workers/peer/manager_res.rs]: Yeah I'd remove the `first` as well

Comment (thibault-martinez) [reply bee-protocol/src/workers/peer/manager_res.rs]: `fair_find` or ` find_fairly` ?

Comment (pvdrz) [reply bee-protocol/src/workers/peer/manager_res.rs]: whatever you prefer. I'd do `find_fairy` :trollface:

Comment (thibault-martinez) [reply bee-protocol/src/workers/peer/manager_res.rs]: Ahah, whatever, you choose

Comment (pvdrz) [reply bee-protocol/src/workers/peer/manager_res.rs]: 🧚‍♂️

File: bee-protocol/src/workers/peer/manager_res.rs [hunk 3]
```diff
@@ -48,64 +55,95 @@ type PeerTuple = (Arc<Peer>, Option<(GossipSender, oneshot::Sender<()>)>);
...
     peers: HashMap<PeerId, PeerTuple>,
     // This is needed to ensure message distribution fairness as iterating over a HashMap is random.
-    // TODO private
-    pub(crate) keys: Vec<PeerId>,
+    keys: Vec<PeerId>,
 }
 
 #[derive(Default)]
-// TODO private
-pub struct PeerManager(pub(crate) RwLock<PeerManagerInner>);
```
Comment (Adam-Gleave) [inline bee-protocol/src/workers/peer/manager_res.rs:57]: This feels like it was always a bad idea :eyes:

**Review by Adam-Gleave — DISMISSED** [review]

File: bee-protocol/src/workers/peer/manager_res.rs (hunk 3 above)
Comment (Alex6323) [reply bee-protocol/src/workers/peer/manager_res.rs:57]: I agree.

Comment (pvdrz) [reply bee-protocol/src/workers/peer/manager_res.rs:57]: Yeah I think we should have some guidelines or compilation checks about locks because I believe that every time we had an issue with the node freezing or not shutting down correctly is because we are using some `RwLock` or `Mutex` in an unstructured way.

File: bee-protocol/src/workers/peer/manager_res.rs [hunk 4]
```diff
@@ -48,64 +55,95 @@ type PeerTuple = (Arc<Peer>, Option<(GossipSender, oneshot::Sender<()>)>);
...
         lock.keys.retain(|peer_id| peer_id != id);
         lock.peers.remove(id)
     }
 
     pub(crate) fn for_each<F: Fn(&PeerId, &Peer)>(&self, f: F) {
-        self.0.read().peers.iter().for_each(|(id, (peer, _))| f(id, peer));
+        self.inner.read().peers.iter().for_each(|(id, (peer, _))| f(id, peer));
+    }
+
+    pub(crate) fn fair_find(&self, f: impl Fn(&Peer) -> bool) -> Option<PeerId> {
```
Comment (Alex6323) [inline bee-protocol/src/workers/peer/manager_res.rs:141]: Not necessarily related to that PR, but I think a little prose to explain why this `fair_find` method is needed could be helpful. Could we use an `IndexMap` here?

Isn't a better method name: `select_peer_randomly` or something?

Comment (pvdrz) [reply bee-protocol/src/workers/peer/manager_res.rs:141]: I think I'm not the right person to answer this as I didn't write the code that inspired this method. 

I also have a couple questions about the `Vec<PeerId>`. The iteration order in `HashMap::keys` is not deterministic between runs but it is consistent if the hashmap has not changed, why is this not enough?

Regarding the name. I favor `find` against `select` because of [`Iterator::find`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.find). About the `randomly` instead of `fairly` I'd say this is not a random traverse, it is consistent if the hashmap does not change.

Comment (thibault-martinez) [reply bee-protocol/src/workers/peer/manager_res.rs:141]: > why this fair_find method is needed could be helpful. Could we use an IndexMap here?

You would still need the method with IndexMap, this is unrelated. The methods ensures a cycle around the peers so that the distribution is fair.

> Isn't a better method name: select_peer_randomly or something?

It's not random though.

> but it is consistent if the hashmap has not changed, why is this not enough?

Precisely because the maps does change a lot.

Comment (pvdrz) [reply bee-protocol/src/workers/peer/manager_res.rs:141]: @thibault-martinez but if the map changes a lot, the vec changes a lot so what difference does it make?

Comment (thibault-martinez) [reply bee-protocol/src/workers/peer/manager_res.rs:141]: Sure but the order is not completely shuffled, it keeps being fair for remaining peers

Comment (pvdrz) [reply bee-protocol/src/workers/peer/manager_res.rs:141]: but removing a key from a hashmap doesn't change the iteration order for the other keys.

Comment (Alex6323) [reply bee-protocol/src/workers/peer/manager_res.rs:141]: Right, I now do better understand why the method was written the way it is, but - coming back to my original point - in order to reduce confusion I think the code is "odd" (with the atomic) enough to add a little bit of explanation. Instead of that rotating "pointer" (modulus counter), one could also go with a ring data structure here, which feels like it would better encode the situation we have here.

Comment (thibault-martinez) [reply bee-protocol/src/workers/peer/manager_res.rs:141]: The point of the counter is to keep the state of where you stopped cycling for a future iteration. See Discord protocol, Christian will try something.

**Review by thibault-martinez — APPROVED** [review]

**Review by Alex6323 — APPROVED** [review]

**Review by Adam-Gleave — APPROVED** [review]

**Review by grtlr — APPROVED** [review]
