### PR TITLE
Fix clippy warnings

### LINKED ISSUE #959: Fix return_self_not_must_use clippy lint

### PR DESCRIPTION
**Pull request by grtlr**
# Description of change

Fix `#[must_use]` clippy lint.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes
- [x] I have updated the CHANGELOG.md, if my changes are significant enough

### CODE REVIEW

**Comment by thibault-martinez** [comment]
I have way more issues to fix locally...

**Comment by grtlr** [comment]
Ah that's a caching problem. Sorry, will delete my `target` dir.

File: bee-storage/bee-storage-rocksdb/src/config.rs [hunk 1]
```diff
@@ -111,7 +114,6 @@ impl RocksDbConfigBuilder {
     pub fn new() -> Self {
         Self::default()
     }
-
```
Comment (thibault-martinez) [inline bee-storage/bee-storage-rocksdb/src/config.rs]: Oh no

**Review by Alex6323 — DISMISSED** [review]

**Review by thibault-martinez — APPROVED** [review]

**Review by Alex6323 — APPROVED** [review]

**Review by Adam-Gleave — APPROVED** [review]
