### PR TITLE
Properly handle responses while downloading snapshots

### LINKED ISSUE #948: Panic while trying to import the delta snapshot file [cpt2 branch]
# Bug description

When trying to run the node from the "chrysalis-pt-2" branch, sometimes the node crashes while trying to import the delta snapshot file:

```bash
2022-01-13 07:54:47 (UTC) bee_ledger::workers::snapshot::import      INFO  Importing delta snapshot file ./snapshots/mainnet/delta_snapshot.bin...
thread 'main' panicked at 'Worker `bee_ledger::workers::snapshot::worker::SnapshotWorker` failed to start: Types(UnsupportedVersion(1, 60)).', /root/bee/bee-node/src/fullnode/builder.rs:103:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fish: “../target/release/bee” terminated by signal SIGABRT (Abort)
```
Printing the delta snapshot file with `cat ./snapshots/mainnet/delta_snapshot.bin` yields:

```html
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

### PR DESCRIPTION
**Pull request by grtlr**
# Description of change

When downloading snapshot files (or their headers), we used to only check if the server responded and not what the actual status code was. This should be fixed by this PR.

## Links to any relevant issues

* #948 

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Checked against Tanglebay, which does not provide a delta snapshot.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes
- [x] I have updated the CHANGELOG.md, if my changes are significant enough

### CODE REVIEW

**Review by Alex6323 — DISMISSED** [review]
lgtm

File: bee-ledger/src/workers/snapshot/download.rs [hunk 1]
```diff
@@ -21,23 +21,30 @@ async fn download_snapshot_header(download_url: &str) -> Result<SnapshotHeader,
...
 
-                    return Ok(SnapshotHeader::unpack(&mut slice)?);
+                        return Ok(SnapshotHeader::unpack(&mut slice)?);
+                    }
                 }
+            } else {
+                debug!(
+                    "Downloading snapshot header failed with status code {:?}.",
+                    res.status()
+                );
```
Comment (Adam-Gleave) [inline bee-ledger/src/workers/snapshot/download.rs:47]: Should this be a `warn!(...)`, to be consistent with the warning at line 171?

Comment (grtlr) [reply bee-ledger/src/workers/snapshot/download.rs:47]: I think we decided on using `debug` for the headers so that we don't spam the log too much.

**Review by Adam-Gleave — DISMISSED** [review]

File: bee-ledger/src/workers/snapshot/download.rs [hunk 2]
```diff
@@ -154,13 +161,17 @@ async fn download_snapshot_file(path: &Path, download_url: &str) -> Result<(), E
...
+                    &mut res.bytes().await.map_err(|_| Error::DownloadingFailed)?.as_ref(),
+                    &mut tokio::fs::File::create(path).await?,
+                )
+                .await?;
+            } else {
+                warn!("Downloading snapshot file failed with status code {:?}.", res.status());
+            }
         }
-        Err(e) => warn!("Downloading snapshot file failed with status code {:?}.", e.status()),
+        Err(e) => debug!("Downloading snapshot failed: {:?}.", e.to_string()),
```
Comment (thibault-martinez) [inline bee-ledger/src/workers/snapshot/download.rs]: Do we download a file only if we managed to download the header ? If yes this should maybe stay as a warning ?

Comment (grtlr) [reply bee-ledger/src/workers/snapshot/download.rs]: You're right, and @Adam-Gleave was also right all along, something was off.

Comment (thibault-martinez) [reply bee-ledger/src/workers/snapshot/download.rs]: But Adam's comment was on the header, so it should actually be debug there ?

**Review by thibault-martinez — APPROVED** [review]

File: bee-ledger/src/workers/snapshot/download.rs (hunk 2 above)
Comment (grtlr) [reply bee-ledger/src/workers/snapshot/download.rs]: Yeah, the header should both be `debug` and the actual snapshot should be `warn`. This is probably what caused Adam to write the comment.

Comment (Adam-Gleave) [reply bee-ledger/src/workers/snapshot/download.rs]: Yes, the inconsistency with the errors was confusing me!

**Review by Adam-Gleave — APPROVED** [review]

**Review by samuel-rufi — APPROVED** [review]
